<a href="https://colab.research.google.com/github/riyawakde16-art/Day13/blob/main/Day14_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.random.randint(10,101,(5,6))
print("Array:",a)
print("Shape:",a.shape)
print("Size",a.size)
print("Data Type:",a.dtype)

Array: [[26 70 63 57 79 61]
 [62 13 84 63 60 99]
 [93 81 60 75 22 66]
 [36 95 73 45 13 49]
 [27 47 26 30 47 87]]
Shape: (5, 6)
Size 30
Data Type: int64


In [5]:
import numpy as np
a=np.random.randint(1,51,20)
print("1-D Array:",a)
print("Minimum:",a.argmin())
print("Miximum:",a.argmax())
print("sum of all elements:",a.sum())
print("Mean:",a.mean())
print("Standard Deviation:",a.std())



1-D Array: [ 3 37  1  6 29  2 41 35 47 28  3 24 38 48 34 49 50 34  3 27]
Minimum: 2
Miximum: 16
sum of all elements: 539
Mean: 26.95
Standard Deviation: 17.200218021874026


In [7]:
import numpy as np
a=np.random.randint(20,81,(4,5))
print("Array:",a)
print("Minimum:",a.min())
print("Maximum:",a.max())
print("Sum:",a.sum())
print("Standard deviation:",a.std())
print("Sum of rows:",a.sum(axis=1))
print("Sum of columns:",a.sum(axis=0))


Array: [[60 24 40 80 20]
 [23 42 23 70 54]
 [39 35 53 48 60]
 [60 72 35 41 70]]
Minimum: 20
Maximum: 80
Sum: 949
Standard deviation: 17.653540721339727
Sum of rows: [224 212 235 278]
Sum of columns: [182 173 151 239 204]


In [13]:
import numpy as np
x=np.arange(1,25)
y=x.reshape(4,6)
print("Reshape into (4,6)",y)
print("Shape:",y.shape)
z=x.reshape(3,8)
print("Reshape into (3,8)",z)
print("Shape:",z.shape)
r=x.reshape(2,3,4)
print("Reshape into (2,3,4)",r)
print("Shape:",r.shape)

Reshape into (4,6) [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)
Reshape into (3,8) [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)
Reshape into (2,3,4) [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [15]:
import numpy as np
x=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("Array:",x)
print("First row:",x[0])
print("Last row:",x[:,-1])
print("Even number:",x[x%2==0])

Array: [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First row: [10 20 30 40]
Last row: [ 40  80 120]
Even number: [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [24]:
import numpy as np
x=np.random.randint(1,101,(5,5))
print("Array:",x)
print("Diagonal:",np.diagonal(x))
print("Grater than 50:",x[x>50])
x[x<30]=0
print("Modified array:",x)


Array: [[68 21 69 98 11]
 [76 90 45 90 74]
 [94 51 41 50  7]
 [74 73 48 76 97]
 [73 85 93 53 57]]
Diagonal: [68 90 41 76 57]
Grater than 50: [68 69 98 76 90 90 74 94 51 74 73 76 97 73 85 93 53 57]
Modified array: [[68  0 69 98  0]
 [76 90 45 90 74]
 [94 51 41 50  0]
 [74 73 48 76 97]
 [73 85 93 53 57]]


In [28]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print("Addition:",a+b)
print("Sunbstraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Power:",a**b)
print("Modulo:",a%b)

Addition: [11 22 33 44]
Sunbstraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [     10     400   27000 2560000]
Modulo: [0 0 0 0]


In [22]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Element-wise Multiplication:",A*B)
print("Matrix Multiplication:",np.dot(A,B))
# Difference
# * multiplies corresponding elements
# dot() performs row x column multiplcation

Element-wise Multiplication: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [27]:
import numpy as np
x=np.random.randn(6,6)
print("Array:",x)
print("Shape:",x.shape)
print("Size:",x.size)
print("Data type:",x.dtype)
print("Index of max:",np.argmax(x))
print("Index of min:",np.argmin(x))
print("Sun=bmatrix:",x[:3,:3])
x=np.abs(x)
print("Mean:",x.mean())

Array: [[ 1.43471635  1.38820849  0.75849273  0.71056239  0.37945311 -3.82790627]
 [ 0.30741795 -0.1679174  -0.60163193  0.87415217  1.28459888 -1.36492472]
 [-1.44486647 -0.53574317 -1.52405522 -1.4481514  -0.01137478  0.34241879]
 [-1.94346241 -0.89307106 -1.24624141 -1.26869403 -0.01780921  0.16967536]
 [ 0.27443835  0.92298359 -0.11695014  1.68637131 -0.34839269  0.07849304]
 [-0.34832018 -0.81462835  1.13704968  0.31710531 -0.51828767 -0.24328181]]
Shape: (6, 6)
Size: 36
Data type: float64
Index of max: 27
Index of min: 5
Sun=bmatrix: [[ 1.43471635  1.38820849  0.75849273]
 [ 0.30741795 -0.1679174  -0.60163193]
 [-1.44486647 -0.53574317 -1.52405522]]
Mean: 0.8542179956517802


In [29]:
import numpy as np
# 10 students, 5 subjects
m = np.random.randint(30, 101, (10, 5))
print("Marks:\n", m)
# Total and average
t = m.sum(axis=1)
a = m.mean(axis=1)
print("Total marks:", t)
print("Average marks:", a)
# Highest & lowest
print("Top student index:", t.argmax())
print("Lowest student index:", t.argmin())
# Class statistics
print("Class mean:", m.mean())
print("Class std:", m.std())
# Top 3 students marks
top3 = np.argsort(t)[-3:]
print("Top 3 students:\n", m[top3])

Marks:
 [[ 42  87  39  51  65]
 [ 75  86  32  58  86]
 [ 68  32  68 100  85]
 [ 38  37  59  31  48]
 [ 60  46  41  90  32]
 [ 79  53  70  39  92]
 [ 86  69  80  94  56]
 [ 84  76  44  58  53]
 [ 52  52  55  30  85]
 [ 42  95  60  99  38]]
Total marks: [284 337 353 213 269 333 385 315 274 334]
Average marks: [56.8 67.4 70.6 42.6 53.8 66.6 77.  63.  54.8 66.8]
Top student index: 6
Lowest student index: 3
Class mean: 61.94
Class std: 20.89536790774453
Top 3 students:
 [[ 75  86  32  58  86]
 [ 68  32  68 100  85]
 [ 86  69  80  94  56]]
