<a href="https://colab.research.google.com/github/riyawakde16-art/Day13/blob/main/day13_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print("Array:",arr)
print("Shape:",arr.shape)
print("Type:",arr.dtype)


Array: [10 20 30 40 50]
Shape: (5,)
Type: int64


In [ ]:
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
print("Array:",a)
print("Shape:",a.shape)
print("Type:",a.dtype)

Array: [[1 2 3]
 [4 5 6]
 [6 7 8]]
Shape: (3, 3)
Type: int64


In [ ]:
import numpy as np
a=np.zeros(8)
b=np.ones((4,4))
c=np.zeros((3,3))
print("1-D Array of 8 Zeros:",a)
print("2-D Array of Shape(4,4):",b)
print("3*3 matrix of Zeros:",c)


1-D Array of 8 Zeros: [0. 0. 0. 0. 0. 0. 0. 0.]
2-D Array of Shape(4,4): [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3*3 matrix of Zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
a=np.arange(0,21,1)
print("Numbers from 0-20 with step 1:",a)
b=np.arange(10,50,2)
print("Even numbers from 10-50:",b)
c=np.arange(5,101,5)
print("Numbers from 5-100 with step 5",c)


Numbers from 0-20 with step 1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even numbers from 10-50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
Numbers from 5-100 with step 5 [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [ ]:
import numpy as np
a=np.linspace(0,5,10)
print("Spaced number between 0-5:",a)
print("Length:",len(a))
b=np.linspace(-10,10,15)
print("Spaced number between -10 to 10:",b)
print("Length:",len(b))

Spaced number between 0-5: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10
Spaced number between -10 to 10: [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [ ]:
import numpy as np
a=np.random.rand(10)
print("Random 1D array:",a)
b=np.random.rand(3,3)
print("Random matrix 3*3:",b)
c=np.random.randint(10,51,(4,5))
print("Random integers(4*5):",c)

Random 1D array: [0.67545431 0.0669701  0.07979303 0.64941025 0.49514428 0.79093088
 0.04738483 0.62676605 0.58622996 0.29518777]
Random matrix 3*3: [[0.55952912 0.17095948 0.54274234]
 [0.29759206 0.45934699 0.04165886]
 [0.7719177  0.28229781 0.7025613 ]]
Random integers(4*5): [[39 45 44 11 46]
 [44 46 31 22 26]
 [33 30 33 15 25]
 [28 32 47 34 40]]


In [ ]:
import numpy as np
v1=np.array([2,4,6,8])
v2=np.array([1,3,5,7])
print("Addition:",v1+v2)
print("Substraction:",v1-v2)
print("Multiplaction:",v1*v2)
print("Dot product:",np.dot(v1,v2))


Addition: [ 3  7 11 15]
Substraction: [1 1 1 1]
Multiplaction: [ 2 12 30 56]
Dot product: 100


In [ ]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Addition:",A+B)
print("Multiplaction using dot:",np.dot(A,B))
print("Multiplaction:",A*B)

Addition: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplaction using dot: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Multiplaction: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
import numpy as np
a=np.random.randint(1,101,(4,4))
print("Array:",a)
print("Shape:",a.shape)
print("Dimenstion:",a.ndim)
print("Size:",a.size)
print("Type:",a.dtype)
print("Minimum:",a.min())
print("Maximum:",a.max())


Array: [[ 9 61 68 51]
 [ 8 35 53 97]
 [88 99 67 86]
 [81 17 99 78]]
Shape: (4, 4)
Dimenstion: 2
Size: 16
Type: int64
Minimum: 8
Maximum: 99


In [ ]:
import numpy as np
a=np.random.randint(1,51,20)
b=a.reshape(4,5)
print("Matrix:",b)
print("Sum:",b.sum())
print("Mean:",b.mean())
print("Standard Deviation:",b.std())
print("Maximum value:",b.max(axis=1))

Matrix: [[25  9 29 44 43]
 [ 6 15  1  8 50]
 [35 22 12 27 18]
 [ 6  5 48 31 35]]
Sum: 469
Mean: 23.45
Standard Deviation: 15.193666443620513
Maximum value: [44 50 35 48]


In [ ]:
import numpy as np
#input
a=int(input("Enter a numbers:"))
#Random numbers
b=np.random.randint(10,100,a)
print("Array:",b)
#Statistics
print("Mean:",np.mean(b))
print("Median:",np.median(b))
print("Standard deviation:",np.std(b))
print("Minimum:",np.min(b))
print("Maximum:",np.max(b))
#Reshape if possible
if a % 2 == 0:
  c = b.reshape(2, a//2)
  print("Reshaped array:",c)
  print("Sum:",c.sum(axis=1))
else:
  print("Cannot Reshape!")


Enter a numbers:8
Array: [70 12 71 84 79 54 96 51]
Mean: 64.625
Median: 70.5
Standard deviation: 24.248389121754048
Minimum: 12
Maximum: 96
Reshaped array: [[70 12 71 84]
 [79 54 96 51]]
Sum: [237 280]
